[Beat.Key]
0=[26]
1=[27]
2=[28]
3=[29]
4=[30]
5=[31]
6=[32]
7=[33]
8=[34]
9=[35]
A=[0]
B=[1]
C=[2]
D=[3]
E=[4]
F=[5]
G=[6]
H=[7]
I=[8]
J=[9]
K=[10]
L=[11]
M=[12]
N=[13]
O=[14]
P=[15]
Q=[16]
R=[17]
S=[18]
T=[19]
U=[20]
V=[21]
W=[22]
X=[23]
Y=[24]
Z=[25]
Esc=[36]
LCtrl=[37]
LShift=[38]
LAlt=[39]
LSystem=[40]
RCtrl=[41]
RShift=[42]
RAlt=[43]
RSystem=[44]
Menu=[45]
LBracket=[46]
RBracket=[47]
SemiColon=[48]
Comma=[49]
Period=[50]
Quote=[51]
Slash=[52]
BackSlash=[53]
Return=[58]
BackSpace=[59]
Left=[71]
Right=[72]
Up=[73]
Down=[74]
F1=[85]
F2=[86]
F3=[87]
F4=[88]
F5=[89]
F6=[90]
F7=[91]
F8=[92]
F9=[93]
F10=[94]
F11=[95]
F12=[96]
1pStart=[16]
1pSelect=[22]
1pKey1=[25]
1pKey2=[18]
1pKey3=[23]
1pKey4=[3]
1pKey5=[2]
1pKey6=[5]
1pKey7=[21]
1pScrUp=[38]
1pScrDown=[37]
2pStart=[46]
2pSelect=[47]
2pKey1=[25]
2pKey2=[18]
2pKey3=[23]
2pKey4=[3]
2pKey5=[2]
2pKey6=[5]
2pKey7=[21]
2pScrUp=[41]
2pScrDown=[42]

[Beat.KeyFunc]
Escape=["Esc"]
Option=["1pStart"]
FlipOption=["1pSelect"]
CloseFolder=["1pKey2","1pKey4","1pKey6","Left","BackSpace"]
DecideMusic=["1pKey1","1pKey3","1pKey5","1pKey7","Return","Right"]
UpMusic=["1pScrUp","Up"]
DownMusic=["1pScrDown","Down"]
ReloadFolder=["8"]
IncrPlacement=["1pKey1"]
DecrPlacement=["1pKey2"]
IncrGaugeType=["1pKey3"]
DecrGaugeType=["1pKey4"]
IncrAssistType=["1pKey5"]
IncrFlip=["1pKey6"]
IncrDisplayArea=["1pKey7"]
1pKey1=["1pKey1"]
1pKey2=["1pKey2"]
1pKey3=["1pKey3"]
1pKey4=["1pKey4"]
1pKey5=["1pKey5"]
1pKey6=["1pKey6"]
1pKey7=["1pKey7"]
1pScr=["1pScrUp","1pScrDown"]
2pKey1=["2pKey1"]
2pKey2=["2pKey2"]
2pKey3=["2pKey3"]
2pKey4=["2pKey4"]
2pKey5=["2pKey5"]
2pKey6=["2pKey6"]
2pKey7=["2pKey7"]
2pScr=["2pScrUp","2pScrDown"]
